name: gas-benchmarks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  gas-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm run test
        working-directory: gas-benchmarks
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          SCROLL_RPC_URL: ${{ secrets.SCROLL_RPC_URL }}
          SUBGRAPH_URL: ${{ secrets.SUBGRAPH_URL }}
          MONERO_FAIL_NODES_API_URL: ${{ vars.MONERO_FAIL_NODES_API_URL }}
          MIN_SAMPLES: ${{ vars.MIN_SAMPLES }}
          BATCH_SIZE_FOR_RPC_CALLS: ${{ vars.BATCH_SIZE_FOR_RPC_CALLS }}
          DELAY_BETWEEN_BATCHES: ${{ vars.DELAY_BETWEEN_BATCHES }}
