name: subgraph

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  subgraph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Codegen and build (mainnet)
        run: |-
          pnpm run codegen
          pnpm run build
        working-directory: subgraph
        env: NETWORK=mainnet

      - name: Codegen and build (sepolia)
        run: |-
          pnpm run codegen
          pnpm run build
        working-directory: subgraph
        env: NETWORK=sepolia

      - name: Test
        run: pnpm run test
        working-directory: subgraph
